### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-yolo-cuda#3]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by julianchen215** [comment]
Hi @joewxboy , can you please assign this issue to me?

**Comment by deepesh85b** [comment]
Hi @joewxboy 
Please assign this to me

**Comment by joewxboy** [comment]
@julianchen215 please let me and @deepesh85b know if you can't get to this in the next 24 hours or so.

**Comment by hari-ajidesh** [comment]
Please add the hacktoberfest-accepted label to this issue
